language: objective-c
osx_image: xcode6.4
script:
    - xctool -scheme 'NSOperationQueue+CompletionBlock' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test
    - xctool -scheme 'NSOperationQueue+CompletionBlock' -sdk macosx test
